apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lumibot

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml

images:
  - name: ghcr.io/aobaiwaki123/lumibot
    newTag: 0.1.0
