apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lumibot

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml

# Dummy secret generator. In a real environment, use ExternalSecrets or SealedSecrets.
secretGenerator:
  - name: lumibot-secrets
    envs:
      - secret.env
